/*
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.rossystem.ide.contentassist.antlr;

import com.google.inject.Inject;
import de.fraunhofer.ipa.rossystem.ide.contentassist.antlr.internal.InternalRosSystemParser;
import de.fraunhofer.ipa.rossystem.services.RosSystemGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class RosSystemParser extends AbstractContentAssistParser {

	@Inject
	private RosSystemGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRosSystemParser createParser() {
		InternalRosSystemParser result = new InternalRosSystemParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getRosSystemAccess().getGroup(), "rule__RosSystem__Group__0");
					put(grammarAccess.getRosSystemAccess().getGroup_3(), "rule__RosSystem__Group_3__0");
					put(grammarAccess.getRosSystemAccess().getGroup_4(), "rule__RosSystem__Group_4__0");
					put(grammarAccess.getRosSystemAccess().getGroup_4_3(), "rule__RosSystem__Group_4_3__0");
					put(grammarAccess.getRosSystemAccess().getGroup_5(), "rule__RosSystem__Group_5__0");
					put(grammarAccess.getRosSystemAccess().getGroup_5_3(), "rule__RosSystem__Group_5_3__0");
					put(grammarAccess.getRosSystemAccess().getGroup_6(), "rule__RosSystem__Group_6__0");
					put(grammarAccess.getRosSystemAccess().getGroup_6_3(), "rule__RosSystem__Group_6_3__0");
					put(grammarAccess.getNameSpacedComponentAccess().getGroup(), "rule__NameSpacedComponent__Group__0");
					put(grammarAccess.getNameSpacedComponentAccess().getGroup_1(), "rule__NameSpacedComponent__Group_1__0");
					put(grammarAccess.getTopicConnectionAccess().getGroup(), "rule__TopicConnection__Group__0");
					put(grammarAccess.getTopicConnectionAccess().getGroup_6(), "rule__TopicConnection__Group_6__0");
					put(grammarAccess.getTopicConnectionAccess().getGroup_11(), "rule__TopicConnection__Group_11__0");
					put(grammarAccess.getServiceConnectionAccess().getGroup(), "rule__ServiceConnection__Group__0");
					put(grammarAccess.getServiceConnectionAccess().getGroup_6(), "rule__ServiceConnection__Group_6__0");
					put(grammarAccess.getRosSystemAccess().getNameAssignment_3_1(), "rule__RosSystem__NameAssignment_3_1");
					put(grammarAccess.getRosSystemAccess().getRosComponentsAssignment_4_2(), "rule__RosSystem__RosComponentsAssignment_4_2");
					put(grammarAccess.getRosSystemAccess().getRosComponentsAssignment_4_3_1(), "rule__RosSystem__RosComponentsAssignment_4_3_1");
					put(grammarAccess.getRosSystemAccess().getTopicConnectionsAssignment_5_2(), "rule__RosSystem__TopicConnectionsAssignment_5_2");
					put(grammarAccess.getRosSystemAccess().getTopicConnectionsAssignment_5_3_1(), "rule__RosSystem__TopicConnectionsAssignment_5_3_1");
					put(grammarAccess.getRosSystemAccess().getServiceConnectionsAssignment_6_2(), "rule__RosSystem__ServiceConnectionsAssignment_6_2");
					put(grammarAccess.getRosSystemAccess().getServiceConnectionsAssignment_6_3_1(), "rule__RosSystem__ServiceConnectionsAssignment_6_3_1");
					put(grammarAccess.getNameSpacedComponentAccess().getNameSpaceAssignment_1_1(), "rule__NameSpacedComponent__NameSpaceAssignment_1_1");
					put(grammarAccess.getNameSpacedComponentAccess().getRosComponentAssignment_2(), "rule__NameSpacedComponent__RosComponentAssignment_2");
					put(grammarAccess.getTopicConnectionAccess().getTopicNameAssignment_1(), "rule__TopicConnection__TopicNameAssignment_1");
					put(grammarAccess.getTopicConnectionAccess().getFromAssignment_5(), "rule__TopicConnection__FromAssignment_5");
					put(grammarAccess.getTopicConnectionAccess().getFromAssignment_6_1(), "rule__TopicConnection__FromAssignment_6_1");
					put(grammarAccess.getTopicConnectionAccess().getToAssignment_10(), "rule__TopicConnection__ToAssignment_10");
					put(grammarAccess.getTopicConnectionAccess().getToAssignment_11_1(), "rule__TopicConnection__ToAssignment_11_1");
					put(grammarAccess.getServiceConnectionAccess().getServiceNameAssignment_1(), "rule__ServiceConnection__ServiceNameAssignment_1");
					put(grammarAccess.getServiceConnectionAccess().getFromAssignment_5(), "rule__ServiceConnection__FromAssignment_5");
					put(grammarAccess.getServiceConnectionAccess().getFromAssignment_6_1(), "rule__ServiceConnection__FromAssignment_6_1");
					put(grammarAccess.getServiceConnectionAccess().getToAssignment_9(), "rule__ServiceConnection__ToAssignment_9");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RosSystemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RosSystemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
