/*
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.componentInterface.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ComponentInterfaceGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ComponentInterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ComponentInterface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentInterfaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_2_1_0 = (RuleCall)cNameAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRosPublishersKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRospublisherAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cRospublisherRosPublisherParserRuleCall_3_2_0 = (RuleCall)cRospublisherAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRospublisherAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cRospublisherRosPublisherParserRuleCall_3_3_1_0 = (RuleCall)cRospublisherAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRosSubscribersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cRossubscriberAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cRossubscriberRosSubscriberParserRuleCall_4_2_0 = (RuleCall)cRossubscriberAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cRossubscriberAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cRossubscriberRosSubscriberParserRuleCall_4_3_1_0 = (RuleCall)cRossubscriberAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRosSrvServersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRosserviceserverAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRosserviceserverRosServiceServerParserRuleCall_5_2_0 = (RuleCall)cRosserviceserverAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRosserviceserverAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRosserviceserverRosServiceServerParserRuleCall_5_3_1_0 = (RuleCall)cRosserviceserverAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRosSrvClientsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRosserviceclientAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRosserviceclientRosServiceClientParserRuleCall_6_2_0 = (RuleCall)cRosserviceclientAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRosserviceclientAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRosserviceclientRosServiceClientParserRuleCall_6_3_1_0 = (RuleCall)cRosserviceclientAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ComponentInterface:
		//	'ComponentInterface'
		//	'{' ('name' name=EString)? ('RosPublishers' '{' rospublisher+=RosPublisher ("," rospublisher+=RosPublisher)* '}')?
		//	('RosSubscribers' '{' rossubscriber+=RosSubscriber ("," rossubscriber+=RosSubscriber)* '}')? ('RosSrvServers' '{'
		//	rosserviceserver+=RosServiceServer ("," rosserviceserver+=RosServiceServer)* '}')? ('RosSrvClients' '{'
		//	rosserviceclient+=RosServiceClient ("," rosserviceclient+=RosServiceClient)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ComponentInterface' '{' ('name' name=EString)? ('RosPublishers' '{' rospublisher+=RosPublisher (","
		//rospublisher+=RosPublisher)* '}')? ('RosSubscribers' '{' rossubscriber+=RosSubscriber (","
		//rossubscriber+=RosSubscriber)* '}')? ('RosSrvServers' '{' rosserviceserver+=RosServiceServer (","
		//rosserviceserver+=RosServiceServer)* '}')? ('RosSrvClients' '{' rosserviceclient+=RosServiceClient (","
		//rosserviceclient+=RosServiceClient)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'ComponentInterface'
		public Keyword getComponentInterfaceKeyword_0() { return cComponentInterfaceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('name' name=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'name'
		public Keyword getNameKeyword_2_0() { return cNameKeyword_2_0; }
		
		//name=EString
		public Assignment getNameAssignment_2_1() { return cNameAssignment_2_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_1_0() { return cNameEStringParserRuleCall_2_1_0; }
		
		//('RosPublishers' '{' rospublisher+=RosPublisher ("," rospublisher+=RosPublisher)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'RosPublishers'
		public Keyword getRosPublishersKeyword_3_0() { return cRosPublishersKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//rospublisher+=RosPublisher
		public Assignment getRospublisherAssignment_3_2() { return cRospublisherAssignment_3_2; }
		
		//RosPublisher
		public RuleCall getRospublisherRosPublisherParserRuleCall_3_2_0() { return cRospublisherRosPublisherParserRuleCall_3_2_0; }
		
		//("," rospublisher+=RosPublisher)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//rospublisher+=RosPublisher
		public Assignment getRospublisherAssignment_3_3_1() { return cRospublisherAssignment_3_3_1; }
		
		//RosPublisher
		public RuleCall getRospublisherRosPublisherParserRuleCall_3_3_1_0() { return cRospublisherRosPublisherParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('RosSubscribers' '{' rossubscriber+=RosSubscriber ("," rossubscriber+=RosSubscriber)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'RosSubscribers'
		public Keyword getRosSubscribersKeyword_4_0() { return cRosSubscribersKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//rossubscriber+=RosSubscriber
		public Assignment getRossubscriberAssignment_4_2() { return cRossubscriberAssignment_4_2; }
		
		//RosSubscriber
		public RuleCall getRossubscriberRosSubscriberParserRuleCall_4_2_0() { return cRossubscriberRosSubscriberParserRuleCall_4_2_0; }
		
		//("," rossubscriber+=RosSubscriber)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//rossubscriber+=RosSubscriber
		public Assignment getRossubscriberAssignment_4_3_1() { return cRossubscriberAssignment_4_3_1; }
		
		//RosSubscriber
		public RuleCall getRossubscriberRosSubscriberParserRuleCall_4_3_1_0() { return cRossubscriberRosSubscriberParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('RosSrvServers' '{' rosserviceserver+=RosServiceServer ("," rosserviceserver+=RosServiceServer)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'RosSrvServers'
		public Keyword getRosSrvServersKeyword_5_0() { return cRosSrvServersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//rosserviceserver+=RosServiceServer
		public Assignment getRosserviceserverAssignment_5_2() { return cRosserviceserverAssignment_5_2; }
		
		//RosServiceServer
		public RuleCall getRosserviceserverRosServiceServerParserRuleCall_5_2_0() { return cRosserviceserverRosServiceServerParserRuleCall_5_2_0; }
		
		//("," rosserviceserver+=RosServiceServer)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//rosserviceserver+=RosServiceServer
		public Assignment getRosserviceserverAssignment_5_3_1() { return cRosserviceserverAssignment_5_3_1; }
		
		//RosServiceServer
		public RuleCall getRosserviceserverRosServiceServerParserRuleCall_5_3_1_0() { return cRosserviceserverRosServiceServerParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('RosSrvClients' '{' rosserviceclient+=RosServiceClient ("," rosserviceclient+=RosServiceClient)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'RosSrvClients'
		public Keyword getRosSrvClientsKeyword_6_0() { return cRosSrvClientsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//rosserviceclient+=RosServiceClient
		public Assignment getRosserviceclientAssignment_6_2() { return cRosserviceclientAssignment_6_2; }
		
		//RosServiceClient
		public RuleCall getRosserviceclientRosServiceClientParserRuleCall_6_2_0() { return cRosserviceclientRosServiceClientParserRuleCall_6_2_0; }
		
		//("," rosserviceclient+=RosServiceClient)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//rosserviceclient+=RosServiceClient
		public Assignment getRosserviceclientAssignment_6_3_1() { return cRosserviceclientAssignment_6_3_1; }
		
		//RosServiceClient
		public RuleCall getRosserviceclientRosServiceClientParserRuleCall_6_3_1_0() { return cRosserviceclientRosServiceClientParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class GraphNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.GraphName");
		private final Keyword cGraphNameKeyword = (Keyword)rule.eContents().get(1);
		
		//GraphName ros::GraphName:
		//	'GraphName' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'GraphName'
		public Keyword getGraphNameKeyword() { return cGraphNameKeyword; }
	}
	public class RosPublisherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosPublisher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosPublisherAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosPublisherKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefPublisherKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPublisherAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cPublisherPublisherCrossReference_6_0 = (CrossReference)cPublisherAssignment_6.eContents().get(0);
		private final RuleCall cPublisherPublisherEStringParserRuleCall_6_0_1 = (RuleCall)cPublisherPublisherCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosPublisher:
		//	{RosPublisher}
		//	'RosPublisher'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefPublisher' publisher=[ros::Publisher|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosPublisher} 'RosPublisher' name=EString? '{' ('ns' ns=EString)? 'RefPublisher' publisher=[ros::Publisher|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosPublisher}
		public Action getRosPublisherAction_0() { return cRosPublisherAction_0; }
		
		//'RosPublisher'
		public Keyword getRosPublisherKeyword_1() { return cRosPublisherKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefPublisher'
		public Keyword getRefPublisherKeyword_5() { return cRefPublisherKeyword_5; }
		
		//publisher=[ros::Publisher|EString]
		public Assignment getPublisherAssignment_6() { return cPublisherAssignment_6; }
		
		//[ros::Publisher|EString]
		public CrossReference getPublisherPublisherCrossReference_6_0() { return cPublisherPublisherCrossReference_6_0; }
		
		//EString
		public RuleCall getPublisherPublisherEStringParserRuleCall_6_0_1() { return cPublisherPublisherEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosSubscriberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosSubscriber");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosSubscriberAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosSubscriberKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefSubscriberKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSubscriberAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSubscriberSubscriberCrossReference_6_0 = (CrossReference)cSubscriberAssignment_6.eContents().get(0);
		private final RuleCall cSubscriberSubscriberEStringParserRuleCall_6_0_1 = (RuleCall)cSubscriberSubscriberCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosSubscriber:
		//	{RosSubscriber}
		//	'RosSubscriber'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefSubscriber' subscriber=[ros::Subscriber|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosSubscriber} 'RosSubscriber' name=EString? '{' ('ns' ns=EString)? 'RefSubscriber'
		//subscriber=[ros::Subscriber|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosSubscriber}
		public Action getRosSubscriberAction_0() { return cRosSubscriberAction_0; }
		
		//'RosSubscriber'
		public Keyword getRosSubscriberKeyword_1() { return cRosSubscriberKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefSubscriber'
		public Keyword getRefSubscriberKeyword_5() { return cRefSubscriberKeyword_5; }
		
		//subscriber=[ros::Subscriber|EString]
		public Assignment getSubscriberAssignment_6() { return cSubscriberAssignment_6; }
		
		//[ros::Subscriber|EString]
		public CrossReference getSubscriberSubscriberCrossReference_6_0() { return cSubscriberSubscriberCrossReference_6_0; }
		
		//EString
		public RuleCall getSubscriberSubscriberEStringParserRuleCall_6_0_1() { return cSubscriberSubscriberEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosServiceServerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosServiceServer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosServiceServerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosServiceServerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefServerKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSrvserverAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSrvserverServiceServerCrossReference_6_0 = (CrossReference)cSrvserverAssignment_6.eContents().get(0);
		private final RuleCall cSrvserverServiceServerEStringParserRuleCall_6_0_1 = (RuleCall)cSrvserverServiceServerCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosServiceServer:
		//	{RosServiceServer}
		//	'RosServiceServer'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefServer' srvserver=[ros::ServiceServer|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosServiceServer} 'RosServiceServer' name=EString? '{' ('ns' ns=EString)? 'RefServer'
		//srvserver=[ros::ServiceServer|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosServiceServer}
		public Action getRosServiceServerAction_0() { return cRosServiceServerAction_0; }
		
		//'RosServiceServer'
		public Keyword getRosServiceServerKeyword_1() { return cRosServiceServerKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefServer'
		public Keyword getRefServerKeyword_5() { return cRefServerKeyword_5; }
		
		//srvserver=[ros::ServiceServer|EString]
		public Assignment getSrvserverAssignment_6() { return cSrvserverAssignment_6; }
		
		//[ros::ServiceServer|EString]
		public CrossReference getSrvserverServiceServerCrossReference_6_0() { return cSrvserverServiceServerCrossReference_6_0; }
		
		//EString
		public RuleCall getSrvserverServiceServerEStringParserRuleCall_6_0_1() { return cSrvserverServiceServerEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosServiceClientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosServiceClient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosServiceClientAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosServiceClientKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefClientKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSrvclientAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSrvclientServiceClientCrossReference_6_0 = (CrossReference)cSrvclientAssignment_6.eContents().get(0);
		private final RuleCall cSrvclientServiceClientEStringParserRuleCall_6_0_1 = (RuleCall)cSrvclientServiceClientCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosServiceClient:
		//	{RosServiceClient}
		//	'RosServiceClient'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefClient' srvclient=[ros::ServiceClient|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosServiceClient} 'RosServiceClient' name=EString? '{' ('ns' ns=EString)? 'RefClient'
		//srvclient=[ros::ServiceClient|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosServiceClient}
		public Action getRosServiceClientAction_0() { return cRosServiceClientAction_0; }
		
		//'RosServiceClient'
		public Keyword getRosServiceClientKeyword_1() { return cRosServiceClientKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefClient'
		public Keyword getRefClientKeyword_5() { return cRefClientKeyword_5; }
		
		//srvclient=[ros::ServiceClient|EString]
		public Assignment getSrvclientAssignment_6() { return cSrvclientAssignment_6; }
		
		//[ros::ServiceClient|EString]
		public CrossReference getSrvclientServiceClientCrossReference_6_0() { return cSrvclientServiceClientCrossReference_6_0; }
		
		//EString
		public RuleCall getSrvclientServiceClientEStringParserRuleCall_6_0_1() { return cSrvclientServiceClientEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class NSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.NS");
		private final Keyword cNSKeyword = (Keyword)rule.eContents().get(1);
		
		//NS NS:
		//	'NS' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'NS'
		public Keyword getNSKeyword() { return cNSKeyword; }
	}
	
	
	private final ComponentInterfaceElements pComponentInterface;
	private final GraphNameElements pGraphName;
	private final RosPublisherElements pRosPublisher;
	private final RosSubscriberElements pRosSubscriber;
	private final RosServiceServerElements pRosServiceServer;
	private final RosServiceClientElements pRosServiceClient;
	private final EStringElements pEString;
	private final NSElements pNS;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ComponentInterfaceGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pComponentInterface = new ComponentInterfaceElements();
		this.pGraphName = new GraphNameElements();
		this.pRosPublisher = new RosPublisherElements();
		this.pRosSubscriber = new RosSubscriberElements();
		this.pRosServiceServer = new RosServiceServerElements();
		this.pRosServiceClient = new RosServiceClientElements();
		this.pEString = new EStringElements();
		this.pNS = new NSElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.fraunhofer.ipa.componentInterface.ComponentInterface".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ComponentInterface:
	//	'ComponentInterface'
	//	'{' ('name' name=EString)? ('RosPublishers' '{' rospublisher+=RosPublisher ("," rospublisher+=RosPublisher)* '}')?
	//	('RosSubscribers' '{' rossubscriber+=RosSubscriber ("," rossubscriber+=RosSubscriber)* '}')? ('RosSrvServers' '{'
	//	rosserviceserver+=RosServiceServer ("," rosserviceserver+=RosServiceServer)* '}')? ('RosSrvClients' '{'
	//	rosserviceclient+=RosServiceClient ("," rosserviceclient+=RosServiceClient)* '}')?
	//	'}';
	public ComponentInterfaceElements getComponentInterfaceAccess() {
		return pComponentInterface;
	}
	
	public ParserRule getComponentInterfaceRule() {
		return getComponentInterfaceAccess().getRule();
	}
	
	//GraphName ros::GraphName:
	//	'GraphName' /* TODO: implement this rule and an appropriate IValueConverter */;
	public GraphNameElements getGraphNameAccess() {
		return pGraphName;
	}
	
	public ParserRule getGraphNameRule() {
		return getGraphNameAccess().getRule();
	}
	
	//RosPublisher:
	//	{RosPublisher}
	//	'RosPublisher'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefPublisher' publisher=[ros::Publisher|EString]
	//	'}';
	public RosPublisherElements getRosPublisherAccess() {
		return pRosPublisher;
	}
	
	public ParserRule getRosPublisherRule() {
		return getRosPublisherAccess().getRule();
	}
	
	//RosSubscriber:
	//	{RosSubscriber}
	//	'RosSubscriber'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefSubscriber' subscriber=[ros::Subscriber|EString]
	//	'}';
	public RosSubscriberElements getRosSubscriberAccess() {
		return pRosSubscriber;
	}
	
	public ParserRule getRosSubscriberRule() {
		return getRosSubscriberAccess().getRule();
	}
	
	//RosServiceServer:
	//	{RosServiceServer}
	//	'RosServiceServer'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefServer' srvserver=[ros::ServiceServer|EString]
	//	'}';
	public RosServiceServerElements getRosServiceServerAccess() {
		return pRosServiceServer;
	}
	
	public ParserRule getRosServiceServerRule() {
		return getRosServiceServerAccess().getRule();
	}
	
	//RosServiceClient:
	//	{RosServiceClient}
	//	'RosServiceClient'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefClient' srvclient=[ros::ServiceClient|EString]
	//	'}';
	public RosServiceClientElements getRosServiceClientAccess() {
		return pRosServiceClient;
	}
	
	public ParserRule getRosServiceClientRule() {
		return getRosServiceClientAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//NS NS:
	//	'NS' /* TODO: implement this rule and an appropriate IValueConverter */;
	public NSElements getNSAccess() {
		return pNS;
	}
	
	public ParserRule getNSRule() {
		return getNSAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
